### ISSUE TITLE
How do you get this working in Realease 18.04

### ISSUE THREAD

**Issue by dankseman** [Microsoft/linux-vm-tools#27]
I was able to get beta versions working with the scripts here (omitting a couple of commands) but it does not work at all on  the release version.  It falls over at this step

git clone https://github.com/jterry75/xrdp-init.git ~/xrdp-init

**Comment by johnkattenhorn** [comment]
@dankseman - it almost worked without change for me; I had to comment out 

`rmmod vsock` 

in install.sh from the ~/xrdp-init/ubuntu/18.04 directory

**Comment by dankseman** [comment]
Do you need to run git clone etc or just go straight to install.sh?

**Comment by dankseman** [comment]
I just saw that about printers.  It worked for me on 18.04 beta.

**Comment by johnkattenhorn** [comment]
No problem - I use this as reference https://www.tenforums.com/virtualization/107147-guide-how-run-ubuntu-18-04-enhanced-mode-hyper-v.html

**Comment by dankseman** [comment]
Well that is the guide I used as well but it fell over in git clone phase.

**Comment by johnkattenhorn** [comment]
What did you get back from `sudo apt install git` ?

**Comment by dankseman** [comment]
I have partly sussed it.  That link has somehow converted the git clone
into a hyperlink and it falls over.  When I use command from original
source it works.

I removed the line as you said, and redid powershell.  I then shut down vm
stopped and started service but it just point blank refuses to kick to xrdp.

**Comment by matthewturner** [comment]
I get a xrdp "Just connecting" screen with a login dialog with several session options (Xorg, X11rdp, Xvnc, console, vnc-any, sesman-any, neutrinordp-any). 

If I choose Xorg, the dialog disappears and times out after about 5 mins. If I choose X11rdp, RDP says that it got disconnected and attempts to reconnect.

I've tried removing the line suggested above `rmmod vsock` and reran the `./install.sh` script but it has no effect. Is there any other steps I need to follow?

Thanks!

**Comment by dankseman** [comment]
I started from scratch, editing install.sh commenting out the two rmmod lines, got to the end of the setup and got this error:

Job for XRDP service failed because the control process exited with error code.

Amy ideas.

**Comment by stijnv1** [comment]
Steps I did:
1. run install.sh with rmmod vsock commented out only
2. reboot vm
3. run script again, saw error about vmw_vsock_vmci_transport. Commented out rmmod vmw_vsock_vmci_transport and rerun the script
4. reboot vm
5. connected to console of VM, asked me for enhanced session, disabled printer mapping. Used Xorg to logon.

**Comment by charliebillen** [comment]
@matthewturner does your VM log you in automatically?

I am able to log in to an enhanced session in using the Xorg option after disabling automatic login.

**Comment by dankseman** [comment]
I am sure this is actually a Hyper-v issue. Even if you have a Windows
guest, it does not connect properly unless the guest has a password. Always
been like that.

**Comment by matthewturner** [comment]
Thanks @charliebillen, @stijnv1 and @dankseman.

I had to comment out both lines (`rmmod vsock` and `rmmod vmw_vsock_vmci_transport`) and disable automatic login. 

The performance isn't quite what I'd hoped but close. Could those two lines affect performance?
Thanks!

**Comment by charliebillen** [comment]
@matthewturner may be wrong but I don't _think_ they'd affect performance.

My potentially incorrect understanding is that those kernel modules allow communication between VMWare guests and hosts, and are removed and replaced with `hv_sock` which does the same for Hyper-V guests and hosts.

There is another issue (https://github.com/jterry75/xrdp-init/issues/28) with reports of slow performance on HiDPI screens.  If you're running on your Surface Pro maybe you're seeing the same thing?

**Comment by jterry75** [comment]
@matthewturner - `vsock` is the `AF_VSOCK` protocol for tcp/ip between virtual machines and any hypervisor. `vmw_vsock_vmci_transport` is the VMWare implementation of `vsock` when running on a VMWare hypervisor and `hv_sock` is the Hyper-V implementation for running on the Windows hypervisor. So the goal is that you are using `hv_sock` + `vsock` to enable the Hyper-V socket connections between host/guest.

**Comment by dankseman** [comment]
So explain to me why it bloody worked perfectly on a beta 1804 but is
complete garbage on release version?

I am so disappointed that the originator of the 16.04 web article has
failed to respond.  Sad!

**Comment by jterry75** [comment]
I think he must of just missed it. @cwilhit - Is very much on top of responses in other instances. I will work on getting this script fixed today for release 18.04.

**Comment by cwilhit** [comment]
Beta releases of 18.04 had the vwmare module loaded by default, so we had that line included in the script because it must be unloaded in order to load hv_sock. I would like to note that these errors complaining about rmmod failing when a module is not loaded is _not_ fatal. It should still continue to work :) 

Nevertheless, we'll remove those lines since they're not needed anymore. We're in the final stages of working with Canonical to get an image pre-configured in our Hyper-V Quick Create gallery, which means users don't even have to mess with manually configuring. Thanks for working with us on this!

**Comment by dankseman** [comment]
Even though I removed those lines, it still fails with an error about the
xrdp service as I said earlier, and then xrdp does not work. I believe the
issue is more complicated.

**Comment by cwilhit** [comment]
Is this a stock 18.04 release .iso you're using from Canonical and did this occur on your first attempt at running the script?

My most recent attempt at running this script was this morning with an .iso from Canonical's website and it ran with no issues. After all, virtual machines are supposed to be reproduceable.

**Comment by dankseman** [comment]
Well, I finally got it working.  I restarted from scratch and did full installation rather than the minimal installation as well.

I actually typed all the commands and this time it worked.  I do not know if this is relevant but I did the edit to install.sh before the chmod command this time, and I also did initial reboot using reboot command rather than shutting down via Hyper-V Taskbar and restarting.

I copied these from cerberus script on www.tenforums.com

Get the scripts from GitHub

$ sudo apt-get update

$ sudo apt install git


$ git clone https://github.com/jterry75/xrdp-init.git ~/xrdp-init



Make the scripts executable and run them...

$ cd ~/xrdp-init/ubuntu/18.04/

Now edit the install.sh file using whatever editor you like (nano, vi etc) 
and comment out these two lines dding a # in front

rmmod vmw_vsock_vmci_ttransport
rmmod vsock

i.e.

rmmod vmw_vsock_vmci_ttransport
rmmod vsock

Save file.

$ sudo chmod +x install.sh

sudo ./install.sh

Reboot VM

$ reboot

Run script again to finish setting up VM

$ cd ~/xrdp-init/ubuntu/18.04/

$ sudo ./install.sh


Shutdown VM completely (I do this from Hyper-V Taskbar)

On Host Windows, run following powershell command (with admin rights)


Set-VM -VMName Ubuntu -EnhancedSessionTransportType HvSocket


Restart VM to kick in to XRDP

In popup box, deselect printers, and choose which drive you want to see.

Login with xorg, and name, password.

Now it is in enhanced mode.

**Comment by sregister** [comment]
Seems like there might be multiple issues at play here. 

For whats is worth I also had issues with stock 18.04. After entering credentials afer xrdp login I just got a blank screen. I followed the microsoft blog documentation and decided to run the 16.04/config-user.sh script which I don't think works right on 18.04. I think I tracked it down to ~/.xsession being out of date--calling unity which got replaced by gnome. 

I replaced 'unity' on the last line with:
env GNOME_SHELL_SESSION_MODE=ubuntu gnome-session --session=ubuntu

Now I'm able to log in.

**Comment by cwilhit** [comment]
Good to see it is working for you! You do not need to run the 16.04's config-user.sh for 18.04.

**Comment by Ephesos** [comment]
Any news on this? My quick create gallery isn't showing an Ubuntu option, just Windows 10 dev environment.

**Comment by worthwhileindustries** [comment]
@Ephesos mine doesn't either. Neither enterprise or professional had it available. I just installed it from the iso and installed this library.

**Comment by cwilhit** [comment]
Still working through a few things to get the experience we want for the user. When it does go live, we'll post a new update on our blog and I'll tweet it out.

**Comment by felipedeveza** [comment]
Waiting anxiously for ubuntu 18.04 on quick start.

**Comment by worthwhileindustries** [comment]
@felipedeveza it's not that difficult to install yourself. Why wait.

**Comment by rob10e** [comment]
@sregister Your solution worked!

**Comment by davidrough** [comment]
Would some one please post there working xsessions file for ubuntu 18.04 ?

**Comment by ajaju** [comment]
Dealt with similar issues as you guys and tried the various remedies suggested here and other places. What worked for me, however, was installing the full version of Ubuntu; I  sweated it out with the minimalist version. Someone somewhere said to run the VM on Gen 1 than Gen 2 but i was adamant on running it on Gen 2. The minimalist installation on Gen 2 was apparently missing some important driver/ and/or process/es  which i didn't get the time to figure out; i hope someone does so that we get to make it work with the minimalist version.

**Comment by pudknocka** [comment]
Don't see any **shared-drives** in the Ubuntu session.
Wonder if there is any issue with **Server 2016**?
E.g. Powershell doesn't know '-EnhancedSessionTransportType HvSocket', 
not sure if that is necessary here.
Other than this, I get full-screen Ubuntu session, through RDP even with convenient auto-login,
but desperate to see my **USB drives**.

**Comment by dankseman** [comment]
You have to be running normal version 1803 to do this as 1709 does not have the powershell upgrade needed.  I am almost certain the same is true of Server 2016.

**Comment by pudknocka** [comment]
Probably, well just from the MS doc (may 31)
[docs.microsoft.com/en-us/windows/desktop/HyperV_v2/msvm-virtualsystemsettingdata](url)
it looks like this parameter is not intended to be added to Server 2016 (maybe not yet)?

How does someone know that he is in **EnhancedSessionMode**, its just not by getting full-screen and Auto-Login?
I don't see anything in the xrdp.log either.

**Comment by dankseman** [comment]
It just works i.e. you get the xrdp login screen. It will not work with 2016 - you will just get the normal linux ligin screen.

Also, it does not work if you use linux autologin.

**Comment by pudknocka** [comment]
@dankseman Don't quite understand whats the difference _linux autologin_ vs _RDP autologin_ could be? 
Even the Clipboard mapping works on my system. 
Just the shared-drives are missing, so apparently the setting of the transport type to _HvSocket_ is needed.
That much I guess, but for the time being, Server 2016 with Build 14393 doesn't have that feature implemented yet, alas

**Comment by cwilhit** [comment]
@pudknocka you need to be running a Windows version of 1803 or newer, like a recent Insider build. That means builds 17134+. Versions earlier than this (like 14393) do not have this feature--you'd need to upgrade to get it.

As for your question about knowing you're in enhanced session mode: you'll have to login through an xrdp login, which has a very distinct baby blue background. Alternatively, in a Hyper-V VMConnect window, hovering over the icons in the toolbar you will see an icon that reads either "Basic Session" or "Enhanced Session"

**Comment by SidShetye** [comment]
@cwilhit why is this issue closed without a fix in the Microsoft VM tools/scripts? As of 10/16/2018, linux auto-login is still kills enhanced sessions upon connecting. This happens on a fresh install and what's worse, the setup wizard happily presents the option to enable auto-login ("It's a trap!"). 

On a side note, Ubuntu 18.04's memory usage is really bloated, apparently due to Gnome (6.5GB idle at login). Do you support enhanced sessions with other desktop managers? If yes, how?
----
For others seeing this and this issue broke gnome terminal, you can disable auto-login by "Show applications" (bottom-left) -> Details -> Users -> [Unlock] (top right) -> Automatic Login -> Off

Or if terminal is working, by `sudo nano /etc/gdm3/custom.conf` and comment out the lines as follows

```
# Enabling automatic login
#  AutomaticLoginEnable = true
#  AutomaticLogin = your_username_here
```

**Comment by cwilhit** [comment]
@SidShetye this issue was opened to track generally getting enhanced mode to work with Ubuntu 18.04 release. If you want to track auto-login, I'd recommend following #22 instead.

**Comment by mvirts** [comment]
Hi!

Posting because I ended up here trying to get Enhanced mode working.

If you're stuck on an older release of Windows 10 and can't use HvSocket, just configure xrdp to listen on tcp, configure networking (make sure your machine can reach the VM over the network), and connect with Remote Desktop Connection (you can add Drive sharing before you connect).

What worked for me:
On my development laptop...
New Gen2 VM, new VHD, install from ubuntu-20.04.1-desktop-amd64.iso
Create new Virtual Switch, external, sharing my wifi adapter with host (This was problematic, but eventually worked, did it 3 times)
wget https://raw.githubusercontent.com/Microsoft/linux-vm-tools/master/ubuntu/18.04/install.sh
run it (chmod +x install.sh; sudo ./install.sh)
reboot, run again per instructions
Nothing changes, go edit /etc/xrdp/xrdp.ini, change port=tcp://:3389
restart xrdpd
try to login with remote desktop, get a black screen???. Killed gnome session manager and I was logged out of both rdp and vm connection.
[messed with xrdp session and gnome config to no avail, tried a few more times]
stay logged out of my session in Virtual Machine Connection
log in over RDP again, works this time. (Maybe gnome won't allow me to log in twice?)

Matt
