### ISSUE TITLE
Not getting device plug n play

### ISSUE THREAD

**Issue by wnelbach** [microsoft/linux-vm-tools#30]
Sorry if this question is out of scope, it seems like this is the only place discussing enhanced sessions for Ubuntu. Anyway, is sound and USB not supported? I want to prevent myself from going down a rabbit trail that leads to no where.

Also, for the sake of adding to this experience....  

I created an Ubuntu 16.04 vm pre-18.04 to see if I would have any success with enhanced sessions. I loaded all of my favorite tools and followed the steps in the blog, unfortunately it was an epic fail. When 18.04 was released I upgraded the 16.04 vm to 18.04 in hopes that the roll out would fix whatever issues I was having (im not an Ubuntu expert).  I Followed the steps to comment out the rmmod lines and ran the install script and still no luck. I then did a fresh install with 18.04, followed the steps and BAM! duel monitors! From there I started to installing my favorite tools only to fined out that some were not supported (MikTex), again no expert and no info online how to resolve the issue. Third shot. 
    1. Made a fresh install of 16.04 
    2. Loaded my tools
    3. Skipped the steps for 16.04 xdrp install
    4. Upgraded to 18.04
    5. Ran the xrdp install for 18.04 /w rmmod commented out
    6. Success...tools and duels!
Thanks to all of you for your contribution in giving me at least two screens with Ubuntu. I can live without the rest.

**Comment by cwilhit** [comment]
Hey there. You are correct, sound and generic USB passthrough are not supported as of today. You should go to Windows Feedback Hub and fill out a request or upvote an existing item (I think there's already one for USB passthrough...but that might be scoped to just Windows VMs).

What are the tools that are not supported (any besides MikTex?), and to what extent does "not supported" mean to you? That would be helpful to us.

**Comment by wnelbach** [comment]
cwilhit-
Sorry for the delayed response. Ok, not 100% down with all the lingo but I think it was certain libraries needed to get MikTex to work. Also, I was using a tool call USB Network Gate that would not work. I tried to look up post that were similar to the issues I was having but not luck.

**Comment by v-wajone** [comment]
Is there a target date for USB passthrough support?

**Comment by cwilhit** [comment]
@v-wajone the state of this is that it's a feature request, so there are no committed dates. For gathering data points: what's the use case you'd be looking to solve with USB passthrough?

**Comment by joel0** [comment]
@cwilhit I might use USB passthrough for booting from flash drives (which might require chainloading through something like Plop Boot Manager).  It would be handy to be able to pass flash drives to VMs for native Linux tools, such as dd or the ability to read ext4 partitions.  I can do this currently with USB-Attached-SCSI flash drives (as hard drives to the VM), because the host Windows thinks they are external hard drives instead of USB mass storage devices.

Another use case is for using hardware that works better (or only works) with a Linux build system and tools.  One specific example is the Texas Instruments SensorTag development kit I'm using for school.  The university highly suggest using Linux for development, which requires flashing through USB.

Another example that I could foresee using is connecting an Android device to a VM.  In the past, Linux tools for working with Android ROMs, bootloaders, and drivers were better than on Windows.

Another case would be software defined radios.  The software on Windows can be flaky and involve many kludges.

I need and like to keep Windows as my primary desktop OS, so I would like to do the above mentioned activities in virtual machines.

**Comment by leiocalyx** [comment]
USB passthrough would be great for using usb smartcards and HSM-s, which in turn could be used for a lot of nice and usefull things. 

I have a Yubikey here which doesn't work on ubuntu, but works on a windows 10 vm.
OpenSC and OpenSSL are a pain to configure on windows.

**Comment by clintonm9** [comment]
Just curious, if we are using generation 2 hypervisor, can we currently do USB passthrough from our Windows host to our Linux guest?

**Comment by cwilhit** [comment]
@clintonm9 do you mean a generation 2 VM? Or a type 2 hypervisor? Regardless, Hyper-V does not support USB passthrough (but you can do some USB redirection via the RDP enhanced mode window like sharing USB drivers)

**Comment by clintonm9** [comment]
@cwilhit Got you, thanks! Yeah, I want to use devices more like USB WiFi adaptors.

**Comment by bbhopesh** [comment]
@cwilhit Is there any timeline on plug and play devices on Ubuntu and other Linux VMs?

I need this feature to do Android development on the VM. Currently, I am able to run Android apps on emulator running inside VM but not able to connect a physical Android device to the VM.

**Comment by wnelbach** [comment]
@bbhopesh

I’ve used USB Redirector by Incentives Pro. For me is was a PITA to set up, but it I was able get my USB to pass through to Hyper-V. However, my school was handing out licenses for VMware so I migrated over. Hope that helps 
incentivespro.com

**Comment by bbhopesh** [comment]
I cannot migrate to VMWare for multiple reasons. I need hyper-v for WSL2, for Docker etc.
I will try USB Redirector but I hope hyper-v supports this out of the box soon. Thanks a lot.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
