### ISSUE TITLE
Missing support for 16.04 with HWE

### ISSUE THREAD

**Issue by Michagogo** [microsoft/linux-vm-tools#56]
Hi, I just found this package and am interested in adapting my 16.04 VM to work with Enhanced Sessions. However, part of the 16.04 script is to install the 4.15-based Azure kernel, which isn't actually necessary on 16.04 systems that have installed the [HWE Stack](https://wiki.ubuntu.com/Kernel/RollingLTSEnablementStack). The question, however, remains what else _is_ still needed on 16.04 that's not necessary on 18.04. I'm guessing that just using the 18.04 script won't work, but it's not clear what edits should be made to the 16.04 version of the script besides removing the kernel installation.

**Comment by cwilhit** [comment]
The main difference between 16.04 and 18.04:
* XRDP versions - 18.04 ships with an XRDP version that let's you turn on vsock. This was missing from the 16.04 version of XRDP (you could add the vsock flag but it wouldn't do anything), which is why we had to build from source.
* hvsocket - In 18.04, this kernel module is available and ready to load. In 16.04, it's not available by default so we pulled down the Azure-based kernel, which is packaged with hvsocket.

**Comment by Michagogo** [comment]
In that case, it sounds like a 16.04 system with the HWE kernel would need
the XRDP change, but not the kernel replacement. Is this correct? It seems
to me that if the user has chosen to use the HWE kernel it would be
undesirable to unnecessarily switch them over to the Azure-optimized one.
And regarding XRDP, is the version currently in xenial suitable, other than
that build flag? If so, I wonder if an SRU proposal to just change that
build option in xenial-updates would be accepted?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
